server:
  port: 9004
spring:
  application:
    name: alibabaCloud-sentinel-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
#配置服务对nacos暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'
